// examples/react-tailwind/src/components/LeftSidebar/LeftSidebar.tsx
import { useMemo } from "react";
import {
  Sidebar,
  SidebarSection,
} from "../../../../tailwind-simple/src/nitro.config";
import cn from "clsx";
import Section from "./Section";
import { baseStyles } from "../../../../tailwind-simple/src/styles/base";

export type LeftSidebarProps = {
  leftSidebar: Sidebar["leftSidebar"];
  currentPagePath: string;
};

const LeftSidebar = ({ leftSidebar, currentPagePath }: LeftSidebarProps) => {
  const sidebarSections = useMemo(
    () =>
      leftSidebar.items.reduce<SidebarSection[]>((col, item, i) => {
        // If the first item is not a section header, create a new container section.
        if (i === 0) {
          if (!item.header) {
            const pesudoSection = { text: "" };
            col.push({ ...pesudoSection, children: [], collapsible: true });
          }
        }
        if (item.header) {
          col.push({
            ...item,
            children: [],
            collapsible: item.collapsible ?? false,
          });
        } else {
          col[col.length - 1].children.push(item);
        }
        return col;
      }, []),
    [leftSidebar.items]
  );

  return (
    <nav
      className={cn(
        "sticky w-full flex flex-col",
        baseStyles.sidebar.topOffset
      )}
      aria-labelledby="grid-right"
    >
      {sidebarSections.map((section) => (
        <div key={section.text} className="w-full border-t">
          <Section
            items={section.children}
            text={section.text}
            collapsible={section.collapsible}
            currentPagePath={currentPagePath}
          />
        </div>
      ))}
    </nav>
  );
};

export default LeftSidebar;

// examples/tailwind-simple/src/components/VitePress/LeftSidebar/LeftSidebar.vue
<script lang="ts" setup>
import { computed } from "@vue/reactivity";
import { SidebarElement, SidebarSection } from "../../../nitro.config";
import Section from "./Section.vue";
import { baseStyles } from "../../../styles/base";
import cn from "clsx";

export type LeftSidebarProps = {
  elements: SidebarElement[];
  currentPagePath: string;
};
const props = defineProps<LeftSidebarProps>();

const sidebarSections = computed(() =>
  props.elements.reduce<SidebarSection[]>((col, item, i) => {
    // If the first item is not a section header, create a new container section.
    if (i === 0) {
      if (!item.header) {
        const pesudoSection = { text: "" };
        col.push({ ...pesudoSection, children: [], collapsible: true });
      }
    }
    if (item.header) {
      col.push({
        ...item,
        children: [],
        collapsible: item.collapsible ?? false,
      });
    } else {
      col[col.length - 1].children.push(item);
    }
    return col;
  }, [])
);
</script>

<template>
  <nav
    :class="cn('sticky w-full flex flex-col', baseStyles.sidebar.topOffset)"
    aria-labelledby="grid-right"
  >
    <div
      class="w-full border-t"
      v-for="section in sidebarSections"
      :key="section.text"
    >
      <Section
        :items="section.children"
        :text="section.text"
        :collapsible="section.collapsible"
        :currentPagePath="currentPagePath"
      />
    </div>
  </nav>
</template>
