// examples/preact-tailwind/src/components/Navbar/Navbar.tsx
import { useMemo } from "preact/hooks";
import { NavBar, NavbarItem } from "../../nitro.config";
import { baseStyles } from "../../styles/base";
import Item from "./Item";
import cn from "clsx";

export type NavbarProps = {
  navbar: NavBar;
};

const Navbar = ({ navbar }: NavbarProps) => {
  const items = useMemo(() => {
    let left: NavbarItem[] = [];
    let right: NavbarItem[] = [];

    navbar.items.forEach((item) => {
      if (item.position === "right") {
        right.push(item);
      } else {
        left.push(item);
      }
    });

    return { left, right };
  }, [navbar]);

  return (
    <nav
      className={cn(
        "w-full z-10 sticky top-0 flex py-4 px-10 bg-white",
        baseStyles.headerHeight
      )}
      title="Top Navigation"
    >
      <div className="flex items-center justify-end gap-x-4 w-full py-2">
        <div className="logo flex mr-4">
          <a className="flex flex-row gap-x-3" href="/">
            <img
              src={navbar.logo.src}
              alt={navbar.logo.alt}
              width={navbar.logo.width}
              height={navbar.logo.height}
            />
            <h1 className="text-xl font-bold">{navbar.title}</h1>
          </a>
        </div>
        <div className="flex-1 grid grid-cols-2">
          <div className="w-full flex flex-row">
            {items.left.map((item) => (
              <Item item={item} />
            ))}
          </div>
          <div className="w-full flex flex-row justify-end">
            {items.right.map((item) => (
              <Item item={item} />
            ))}
          </div>
        </div>
      </div>
    </nav>
  );
};

export default Navbar;

// examples/tailwind-simple/src/components/VitePress/Navbar/Navbar.vue
<script lang="ts" setup>
import { NAVBAR, NavbarItem } from "../../../nitro.config";
import { baseStyles } from "../../../styles/base";
import cn from "clsx";
import Item from "./Item.vue";

const { logo, title, items } = NAVBAR;
const { headerHeight } = baseStyles;

let leftItems: NavbarItem[] = [];
let rightItems: NavbarItem[] = [];

items.forEach((item) => {
  if (item.position === "right") {
    rightItems.push(item);
  } else {
    leftItems.push(item);
  }
});
</script>

<template>
  <nav
    :class="
      cn('w-full z-10 sticky top-0 flex py-4 px-10 bg-white', headerHeight)
    "
    title="Top Navigation"
  >
    <div class="flex items-center justify-end gap-x-4 w-full py-2">
      <div class="logo flex mr-4">
        <a class="flex flex-row gap-x-3" href="/">
          <img
            :src="NAVBAR.logo.src"
            :alt="logo.alt"
            :width="logo.width"
            :height="logo.height"
          />
          <h1 class="text-xl font-bold">{{ title }}</h1>
        </a>
      </div>
      <div class="flex-1 grid grid-cols-2">
        <div class="w-full flex flex-row">
          <Item v-for="item in leftItems" :item="item" />
        </div>
        <div class="w-full flex flex-row justify-end">
          <Item v-for="item in rightItems" :item="item" />
        </div>
      </div>
    </div>
  </nav>
</template>
