// examples/tailwind-simple/src/components/Svelte/Navbar/Item.svelte
<script lang="ts">
  import { NavbarItem, isInteriorLink } from "../../../nitro.config";

  export let item: NavbarItem;
</script>

{#if isInteriorLink(item)}
  <a class="text-lg font-medium" href={item.to}>
    {item.label}
  </a>
{:else}
  <a
    href={item.href}
    target="_blank"
    rel="noopener noreferer"
    class="flex my-auto"
  >
    {#if item.icon}
      <img
        src={item.icon.src}
        width={item.icon.width}
        height={item.icon.height}
        alt={item.icon.alt}
      />
    {:else}
      <p v-else class="my-auto">{item.label}}</p>
    {/if}
  </a>
{/if}

// examples/react-tailwind/src/components/Navbar/Item.tsx
import { isExteriorLink, isInteriorLink, NavbarItem } from "../../nitro.config";

export type ItemProps = {
  item: NavbarItem;
};

const Item = ({ item }: ItemProps) => {
  if (isInteriorLink(item)) {
    return (
      <a className="text-lg font-medium" href={item.to}>
        {item.label}
      </a>
    );
  }

  if (isExteriorLink(item)) {
    return (
      <a
        href={item.href}
        target="_blank"
        rel="noopener noreferer"
        className="flex my-auto"
      >
        {item.icon ? (
          <img
            src={item.icon.src}
            width={item.icon.width}
            height={item.icon.height}
            alt={item.icon.alt}
          />
        ) : (
          <p className="my-auto">{item.label}</p>
        )}
      </a>
    );
  }

  return null;
};

export default Item;
