// examples/tailwind-simple/src/components/VitePress/Navbar/Item.vue
<script lang="ts" setup>
import {
  NavbarItem,
  isExteriorLink,
  isInteriorLink,
} from "../../../nitro.config";

defineProps<{
  item: NavbarItem;
}>();
</script>

<template>
  <a v-if="isInteriorLink(item)" class="text-lg font-medium" :href="item.to">
    {{ item.label }}
  </a>
  <a
    v-if="isExteriorLink(item)"
    :href="item.href"
    target="_blank"
    rel="noopener noreferer"
    class="flex my-auto"
  >
    <img
      v-if="item.icon"
      :src="item.icon.src"
      :width="item.icon.width"
      :height="item.icon.height"
      :alt="item.icon.alt"
    />
    <p v-else class="my-auto">{{ item.label }}</p>
  </a>
</template>

// examples/react-tailwind/src/components/Navbar/Item.tsx
import { isExteriorLink, isInteriorLink, NavbarItem } from "../../nitro.config";

export type ItemProps = {
  item: NavbarItem;
};

const Item = ({ item }: ItemProps) => {
  if (isInteriorLink(item)) {
    return (
      <a className="text-lg font-medium" href={item.to}>
        {item.label}
      </a>
    );
  }

  if (isExteriorLink(item)) {
    return (
      <a
        href={item.href}
        target="_blank"
        rel="noopener noreferer"
        className="flex my-auto"
      >
        {item.icon ? (
          <img
            src={item.icon.src}
            width={item.icon.width}
            height={item.icon.height}
            alt={item.icon.alt}
          />
        ) : (
          <p className="my-auto">{item.label}</p>
        )}
      </a>
    );
  }

  return null;
};

export default Item;
